### ISSUE TITLE
The result of ABSOLUTE v1.0.6 cannot be used

### ISSUE THREAD

**Issue by Jonathanyu2014** [broadinstitute/PhylogicNDT#4]
As the manual says, Absolute annotated mafs or .Rdata files can be used as the input for PhylogicNDT.However, ABSOLUTE V1.06 can only output the CCF of the first mutation. Others are NAs. Besides, the R script "rdata_extractor.R"  extracts "seg.obj$mode.res$SSNV.ccf.dens" from the RData file of ABSOLTUE, while it DOES NOT exist in the RData file from ABSOLUTE. Can the author provide another version of ABSOLUTE whose RData file contains seg.obj$mode.res$SSNV.ccf.dens ?

**Comment by Jonathanyu2014** [comment]
I find seg.obj[["mode.res"]][["subclonal_SCNA_res"]][["CCF_dens"]]  in *called.RData, while the CCF are all NA except the first mutation.

**Comment by iglc** [comment]
You need a later version of Absolute that runs on WES data. 
You can also use output of other tools if you reformat accordingly.

**Comment by alipsky** [comment]
Im working with the tool as well, very much looking forward to getting it up and running but I'm  also hung up on the  "seg.obj$mode.res$SSNV.ccf.dens" missing in the RData along with CCF histograms for anything other than the first mutation.  I do not see information for newer versions of absolute posted only, can you point in the right direction?

**Comment by alipsky** [comment]
iglc, can you recommend another CNV tools that is compatible which can generate the histograms?  Any way to do this with PureCN?

**Comment by abenjak** [comment]
To generate the CCF histograms in ABSOLUTEv1.06, for all the mutations in the MAF, modify the source file `ABSOLUTE_1.0.6/R/write_called_SEG_MAF.R`, line 44:
from
`      for (i in seq_along(nrow(mut_dat))) {`
to
`      for (i in seq(nrow(mut_dat))) {`

The `*MAF.txt` produced by `ExtractReviewedResults` will now have the CCF histograms for all mutations.

**Comment by Jonathanyu2014** [comment]
Thank you @abenjak. This problem was finally  solved. I think I need to learn R hard, and I hope I can fix simailar bugs by myself oneday.
