### ISSUE TITLE
ModuleNotFoundError: No module named 'Sample'

### ISSUE THREAD

**Issue by vicentepp** [broadinstitute/PhylogicNDT#44]
Hello,
I just cloned PhylogicNDT repostitory and I am trying to run it and I get the following error when running:
'./PhylogicNDT.py Cluster -i Patient_ID  -s Sample1_id:Sample1_maf:Sample1_CN_seg:Sample1_Purity:Sample1_Timepoint -s Sample2_id:Sample2_maf:Sample2_CN_seg:Sample2_Purity:Sample2_Timepoint ... SampleN_info '
C:\Users\Vicente\python\Phylogic\PhylogicNDT\phylogicndt.log
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\python\Phylogic\PhylogicNDT\PhylogicNDT.py in <module>
     28 import BuildTree.CellPopulation
     29 import GrowthKinetics.GrowthKinetics
---> 30 import SinglePatientTiming.SinglePatientTiming
     31 import LeagueModel.LeagueModel
     32 

~\python\Phylogic\PhylogicNDT\SinglePatientTiming\SinglePatientTiming.py in <module>
      2 import numpy as np
      3 import itertools
----> 4 from data.Patient import Patient
      5 import TimingEngine
      6 from output.PhylogicOutput import PhylogicOutput

~\python\Phylogic\PhylogicNDT\data\Patient.py in <module>
      2 # Patient - central class to handle and store sample CCF data
      3 ##########################################################
----> 4 from Sample import TumorSample
      5 from Sample import RNASample
      6 from SomaticEvents import SomMutation, CopyNumberEvent

ModuleNotFoundError: No module named 'Sample'

How can I solve this?
I am pretty new to Python, so I would appreciate any help. I am using Jupyter to run this. Thanks!

**Comment by THT-sleepy** [comment]
Hello there,

Could you please tell how did you solve the problem at last? I have met the same problem and I have no idea on solving it.

Best
Huatao
